# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - node_modules

language: node_js

node_js:
    - "8"

notifications:
    email: false
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/0913a4ced1f3322b4c40
        on_success: change # options: [always|never|change] default: always
        on_failure: always # options: [always|never|change] default: always
        on_start: false # default: false

before_script:
    - npm install -g grunt-cli

script:
    - npm run test:ci

addons:
    sauce_connect: false 

env:
    global:
        - SAUCE_USERNAME: 'mediumeditor'
        - SAUCE_ACCESS_KEY: '714bc135-e615-453a-bb59-0a52e5cd9917'
